# Generated by Django 5.1 on 2024-08-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Тип топлива'},
        ),
        migrations.AlterModelOptions(
            name='transmissiontype',
            options={'verbose_name': 'Тип КПП'},
        ),
        migrations.AlterModelTable(
            name='fueltype',
            table='fuel_type',
        ),
        migrations.AlterModelTable(
            name='transmissiontype',
            table='transmission_type',
        ),
    ]
