version: '3'

services:
  web:
    build: ..
    container_name: car-api
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
